# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-16 12:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_base', '0002_menu_project'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prize',
            name='marquee_image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prize_as_marquee', to='django_base.ImageModel', verbose_name='跑马灯图案'),
        ),
        migrations.AlterField(
            model_name='prize',
            name='marquee_size',
            field=models.CharField(choices=[('BIG', '大'), ('MEDIUM', '中'), ('SMALL', '小')], default='SMALL', max_length=20, verbose_name='跑马灯大小'),
        ),
    ]
