# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='age',
            field=models.IntegerField(default=0, help_text='如果为0则根据birthday判定年龄，否则使用此数字作为年龄', verbose_name='年龄'),
        ),
    ]
