# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 11:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creditcointransaction',
            options={'verbose_name': '金币流水', 'verbose_name_plural': '金币流水'},
        ),
        migrations.AlterModelOptions(
            name='creditdiamondtransaction',
            options={'verbose_name': '钻石流水', 'verbose_name_plural': '钻石流水'},
        ),
        migrations.AlterModelOptions(
            name='creditstarindextransaction',
            options={'verbose_name': '星光指数流水', 'verbose_name_plural': '星光指数流水'},
        ),
        migrations.AlterModelOptions(
            name='creditstartransaction',
            options={'verbose_name': '星星流水', 'verbose_name_plural': '星星流水'},
        ),
        migrations.AlterModelOptions(
            name='dailycheckinlog',
            options={'verbose_name': '每日签到', 'verbose_name_plural': '每日签到'},
        ),
        migrations.AlterModelOptions(
            name='leveloption',
            options={'verbose_name': '等级设定', 'verbose_name_plural': '等级设定'},
        ),
    ]
