# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-28 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_member_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='experience',
            field=models.IntegerField(default=0, verbose_name='经验值'),
        ),
    ]
