# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170619_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='date_ilive_sig_expire',
            field=models.DateTimeField(blank=True, help_text='默认过期时间为180天', null=True, verbose_name='iLive鉴权密钥过期时间'),
        ),
        migrations.AddField(
            model_name='member',
            name='ilive_sig',
            field=models.TextField(blank=True, default='', help_text='长度320位，由ilive模块封装的腾讯云SDK产生', verbose_name='iLive鉴权密钥'),
        ),
    ]
