# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-27 17:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170619_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeevent',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='創建時間'),
            preserve_default=False,
        ),
    ]
