# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-16 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170716_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prize',
            name='date_sticker_begin',
            field=models.DateField(blank=True, null=True, verbose_name='表情包有效期开始'),
        ),
        migrations.AlterField(
            model_name='prize',
            name='date_sticker_end',
            field=models.DateField(blank=True, null=True, verbose_name='表情包有效期结束'),
        ),
        migrations.AlterField(
            model_name='prize',
            name='marquee_size',
            field=models.CharField(choices=[('LARGE', '大'), ('MEDIUM', '中'), ('SMALL', '小')], default='SMALL', max_length=20, verbose_name='跑马灯大小'),
        ),
    ]
