# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-16 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170716_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='prizetransaction',
            name='source_tag',
            field=models.CharField(choices=[('ACTIVITY', '活動禮物'), ('STAR_BOX', '寶盒禮物'), ('ACTIVITY', 'VIP回饋禮物')], default='ACTIVITY', max_length=20, verbose_name='流水类型'),
            preserve_default=False,
        ),
    ]
