# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-28 12:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_member_experience'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='member',
        #     name='vip_level',
        # ),
    ]
