# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-28 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170627_1632'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='member',
        #     name='ilive_sig',
        #     field=models.TextField(blank=True, default='', help_text='由ilive模块封装的腾讯云SDK产生', verbose_name='iLive鉴权密钥'),
        # ),
    ]
