# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-16 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_prizetransaction_source_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditstarindexreceivertransaction',
            name='type',
            field=models.CharField(choices=[('GENERATE', '送禮產生'), ('BOX_EXPENSE', '寶盒消耗')], default='GENERATE', max_length=20, verbose_name='流水类型'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditstarindexsendertransaction',
            name='type',
            field=models.CharField(choices=[('GENERATE', '送禮產生'), ('BOX_EXPENSE', '寶盒消耗')], default='GENERATE', max_length=20, verbose_name='流水类型'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditstartransaction',
            name='type',
            field=models.CharField(choices=[('LIVE_GIFT', '直播赠送'), ('EARNING', '任務獲得'), ('ADMIN', '後臺補償')], default='ADMIN', max_length=20, verbose_name='流水类型'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='creditcointransaction',
            name='type',
            field=models.CharField(choices=[('ADMIN', '管理員發放'), ('LIVE_GIFT', '直播赠送'), ('RECHARGE', '充值'), ('EXCHANGE', '兌換')], max_length=20, verbose_name='流水类型'),
        ),
        migrations.AlterField(
            model_name='creditdiamondtransaction',
            name='type',
            field=models.CharField(choices=[('ADMIN', '管理員發放'), ('LIVE_GIFT', '直播赠送'), ('EXCHANGE', '兌換'), ('WITHDRAW', '提現'), ('ACTIVITY_EXPENSE', '活動消費')], max_length=20, verbose_name='流水类型'),
        ),
        migrations.AlterField(
            model_name='prizetransaction',
            name='source_tag',
            field=models.CharField(choices=[('ACTIVITY', '活動禮物'), ('STAR_BOX', '寶盒禮物'), ('VIP', 'VIP回饋禮物'), ('SHOP', '商店購買')], max_length=20, verbose_name='流水类型'),
        ),
    ]
