# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-28 12:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_member_vip_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activeevent',
            name='like_count',
        ),
    ]
