# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-28 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170628_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='livewatchlog',
            name='duration',
            field=models.IntegerField(default=0, verbose_name='停留時長'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livewatchlog',
            name='status',
            field=models.CharField(choices=[('NORMAL', '正常'), ('SILENT', '禁言'), ('SPEAK', '连麦')], default='NORMAL', max_length=20, verbose_name='狀態'),
        ),
    ]
