# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-18 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170716_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='date_approved',
            field=models.DateTimeField(blank=True, null=True, verbose_name='审批通过时间'),
        ),
    ]
