# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-28 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20170628_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livewatchlog',
            name='date_leave',
            field=models.DateTimeField(blank=True, null=True, verbose_name='退出时间'),
        ),
        migrations.AlterField(
            model_name='livewatchlog',
            name='duration',
            field=models.IntegerField(default=0, verbose_name='停留時長'),
        ),
    ]
