# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-28 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_live_like_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='live',
            name='like_count',
            field=models.IntegerField(default=0, verbose_name='点赞数量'),
        ),
    ]
