# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-18 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_familymember_date_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='familyarticle',
            name='content',
            field=models.TextField(blank=True, default='', verbose_name='内容'),
        ),
    ]
