# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-28 12:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_activeevent_like_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='content',
        ),
    ]
