# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-18 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_familyarticle_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymission',
            name='item',
            field=models.CharField(choices=[('WATCH_MASTER_PRIZE', '送家族长礼物额度'), ('WATCH_MASTER_DURATION', '观看家族长直播时长'), ('COUNT_WATCH_LOG', '累计观看数'), ('COUNT_FOLLOWED', '陌生人追踪你的个数'), ('COUNT_FRIEND', '拥有的好友数'), ('COUNT_LOGIN', '连续登录天数'), ('COUNT_INVITE', '邀请好友注册数'), ('COUNT_SHARE_MASTER_LIVE', '分享家族长直播的分享数'), ('COUNT_WATCH_MASTER_LIVE', '在家族长直播间的访谈数'), ('COUNT_LIVE', '连续开播的天数'), ('COUNT_RECEIVE_DIAMOND', '收到钻石额度')], default='WATCH_MASTER_PRIZE', max_length=50, verbose_name='任务元件'),
        ),
        migrations.AddField(
            model_name='familymission',
            name='item_value',
            field=models.IntegerField(blank=True, default=0, help_text='指定条件达到所需的数值', verbose_name='元件数值'),
        ),
    ]
