# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-18 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20170718_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymission',
            name='date_begin',
            field=models.DateField(blank=True, null=True, verbose_name='任务开始时间'),
        ),
        migrations.AddField(
            model_name='familymission',
            name='date_end',
            field=models.DateField(blank=True, null=True, verbose_name='任务结束时间'),
        ),
    ]
