# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-28 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_movie_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='content',
            field=models.TextField(blank=True, default='', verbose_name='内容'),
        ),
    ]
