# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-05 11:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170628_1553'),
        ('core', '0008_auto_20170704_0001'),
    ]

    operations = [
    ]
