# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20170705_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='live',
            name='password',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='房间密码'),
        ),
    ]
