# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 09:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20170705_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='live',
            name='push_url',
        ),
    ]
