# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 14:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_live_push_url'),
        ('core', '0008_auto_20170704_0001'),
    ]

    operations = [
    ]
