# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-18 16:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20170718_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='family_introduce',
            field=models.TextField(blank=True, default='', null=True, verbose_name='家族简介'),
        ),
        migrations.AlterField(
            model_name='familymission',
            name='badge',
            field=models.ForeignKey(blank=True, help_text='当选择的奖励元件为徽章时添加', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='family_missions', to='core.Badge', verbose_name='奖励徽章'),
        ),
    ]
