# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-28 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_movie_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='播放次数'),
        ),
    ]
