# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 17:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_base', '0004_merge_20170706_1429'),
        ('core', '0011_merge_20170706_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='core.Activity', verbose_name='活动')),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_pages', to='django_base.ImageModel', verbose_name='海报')),
            ],
            options={
                'verbose_name': '活动页',
                'db_table': 'core_activity_page',
                'verbose_name_plural': '活动页',
            },
        ),
        migrations.CreateModel(
            name='VirboCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='名称')),
                ('is_del', models.BooleanField(default=False, verbose_name='已删除')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('is_sticky', models.BooleanField(default=False, verbose_name='是否置顶')),
                ('sorting', models.SmallIntegerField(default=0, help_text='数字越大越靠前', verbose_name='排序')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('status', models.CharField(choices=[('PENDING', '未领取'), ('ACCEPTED', '已领取'), ('EXPIRED', '已过期')], default='PENDING', max_length=20, verbose_name='状态')),
                ('validity_days', models.IntegerField(default=10, help_text='有效期天数', verbose_name='有效期')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='virbocards_owned', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('image_background', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='virbo_cards_as_background', to='django_base.ImageModel', verbose_name='背景图')),
                ('image_card', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='virbo_cards', to='django_base.ImageModel', verbose_name='虚宝卡')),
            ],
            options={
                'verbose_name': '虚宝卡',
                'db_table': 'core_virbo_card',
                'verbose_name_plural': '虚宝卡',
            },
        ),
    ]
