# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-18 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20170718_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('VOTE', '票选'), ('WATCH', '观看直播'), ('DRAW', '抽奖'), ('DIAMOND', '累计钻石')], default='VOTE', max_length=20, verbose_name='活动类型'),
        ),
    ]
