# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-19 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20170719_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='join_message',
            field=models.CharField(blank=True, help_text='用户在申请加入家族的时候填写的信息', max_length=255, null=True, verbose_name='加入信息'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='称号'),
        ),
    ]
