# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-08 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_activitypage_virbocard'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeevent',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否有效'),
        ),
    ]
