# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-08 09:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_merge_20170705_1122'),
        ('core', '0012_activitypage_virbocard'),
    ]

    operations = [
    ]
