# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-10 10:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_merge_20170708_0913'),
        ('core', '0013_activeevent_is_active'),
    ]

    operations = [
    ]
