# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-28 13:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_movie_live'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginrecord',
            name='author',
        ),
        migrations.DeleteModel(
            name='LoginRecord',
        ),
    ]
