# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 16:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20170719_1505'),
        ('core', '0012_activity_type'),
    ]

    operations = [
    ]
