# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_merge_20170708_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='subject',
            field=models.CharField(choices=[('HOT', '热门页面'), ('VIDEO', '节目页面'), ('ACTIVITY', '活动页面')], default='', max_length=20, verbose_name='主题'),
        ),
    ]
