# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-08 09:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_merge_20170708_0913'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creditstarindextransaction',
            options={'verbose_name': '星光指数（元氣）流水', 'verbose_name_plural': '星光指数（元氣）流水'},
        ),
        migrations.AddField(
            model_name='prizeorder',
            name='coin_transition',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prize_orders', to='core.CreditCoinTransaction', verbose_name='金幣消費记录'),
        ),
        migrations.AddField(
            model_name='prizeorder',
            name='diamond_transition',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prize_orders', to='core.CreditDiamondTransaction', verbose_name='主播鑽石记录'),
        ),
        migrations.AlterField(
            model_name='prizeorder',
            name='prize_transition',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prize_orders', to='core.PrizeTransition', verbose_name='礼物记录'),
        ),
    ]
