# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-26 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_merge_20170719_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='starboxrecord',
            name='star_box',
        ),
        migrations.AddField(
            model_name='prize',
            name='star_box_quantity',
            field=models.IntegerField(default=0, help_text='此禮物在元氣寶盒中出現時的贈送數量，０爲不會在元氣寶盒中出現', verbose_name='元氣寶盒抽中數量'),
        ),
        migrations.AddField(
            model_name='starboxrecord',
            name='coin_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='star_box_record', to='core.CreditCoinTransaction', verbose_name='金幣记录'),
        ),
        migrations.AddField(
            model_name='starboxrecord',
            name='diamond_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='star_box_record', to='core.CreditDiamondTransaction', verbose_name='鑽石记录'),
        ),
        migrations.AddField(
            model_name='starboxrecord',
            name='prize_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='star_box_record', to='core.PrizeTransaction', verbose_name='礼物记录'),
        ),
        migrations.AddField(
            model_name='starboxrecord',
            name='receiver_star_index_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='star_box_records', to='core.CreditStarIndexReceiverTransaction', verbose_name='主播元气指數记录'),
        ),
        migrations.AddField(
            model_name='starboxrecord',
            name='sender_star_index_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='star_box_records', to='core.CreditStarIndexSenderTransaction', verbose_name='觀衆元气指數记录'),
        ),
    ]
