# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-25 16:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0014_merge_20170719_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_type', models.CharField(choices=[('RECEIVE_DIAMOND', '接收鑽石數'), ('SEND_DIAMOND', '送出鑽石數'), ('STAR_INDEX', '元氣指數')], max_length=20, verbose_name='排行類型')),
                ('duration', models.CharField(choices=[('DATE', '每日'), ('WEEK', '每週'), ('TOTAL', '統計')], max_length=20, verbose_name='統計區間')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='數量')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rankrecords_owned', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name_plural': '排行榜記錄',
                'db_table': 'core_rank_record',
                'verbose_name': '排行榜記錄',
            },
        ),
    ]
