# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-08 09:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20170708_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prizeorder',
            name='coin_transition',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prize_orders', to='core.CreditCoinTransaction', verbose_name='金幣消費记录'),
        ),
        migrations.AlterField(
            model_name='prizeorder',
            name='diamond_transition',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prize_orders', to='core.CreditDiamondTransaction', verbose_name='主播鑽石记录'),
        ),
    ]
