# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-31 09:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_loginrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityparticipation',
            name='coin_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_participation', to='core.CreditCoinTransaction', verbose_name='金币奖励记录'),
        ),
        migrations.AddField(
            model_name='activityparticipation',
            name='diamond_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_participation', to='core.CreditDiamondTransaction', verbose_name='钻石奖励记录'),
        ),
        migrations.AlterField(
            model_name='creditcointransaction',
            name='type',
            field=models.CharField(choices=[('ADMIN', '管理員發放'), ('LIVE_GIFT', '直播赠送'), ('RECHARGE', '充值'), ('EXCHANGE', '兌換'), ('BOX', '打開元氣寶盒'), ('BARRAGE', '發送彈幕消費'), ('FAMILY_MODIFY', '家族長修改頭銜'), ('DAILY', '每日签到获得'), ('ACTIVITY', '活动')], max_length=20, verbose_name='流水类型'),
        ),
        migrations.AlterField(
            model_name='creditdiamondtransaction',
            name='type',
            field=models.CharField(choices=[('ADMIN', '管理員發放'), ('LIVE_GIFT', '直播赠送'), ('EXCHANGE', '兌換'), ('WITHDRAW', '提現'), ('ACTIVITY_EXPENSE', '活動消費'), ('BOX', '开启元气宝盒'), ('ACTIVITY', '活动')], max_length=20, verbose_name='流水类型'),
        ),
    ]
