# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-08 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20170708_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='prizetransition',
            name='prize_count',
            field=models.IntegerField(default=1, verbose_name='礼物数量'),
        ),
    ]
