# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-12 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20170712_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='prizecategory',
            name='is_vip_only',
            field=models.BooleanField(default=False, verbose_name='是否VIP专属'),
        ),
    ]
