# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-08 11:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_prizetransition_prize_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prizetransition',
            name='prize_count',
        ),
    ]
