# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-26 18:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20170725_1808'),
        ('core', '0015_auto_20170726_1550'),
    ]

    operations = [
    ]
