# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-04 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20170831_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityparticipation',
            name='status',
            field=models.CharField(choices=[('ACTIVE', '进行中'), ('EXPIRED', '超时未达成'), ('COMPLETE', '完成')], default='ACTIVE', max_length=20, verbose_name='参与状态'),
        ),
    ]
