# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-26 19:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_merge_20170726_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='livebarrage',
            name='credit_coin_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='barrage', to='core.CreditCoinTransaction', verbose_name='扣除金幣記錄'),
        ),
        migrations.AlterField(
            model_name='creditcointransaction',
            name='type',
            field=models.CharField(choices=[('ADMIN', '管理員發放'), ('LIVE_GIFT', '直播赠送'), ('RECHARGE', '充值'), ('EXCHANGE', '兌換'), ('BOX', '打開元氣寶盒'), ('BARRAGE', '發送彈幕消費')], max_length=20, verbose_name='流水类型'),
        ),
        migrations.AlterField(
            model_name='creditdiamondtransaction',
            name='type',
            field=models.CharField(choices=[('ADMIN', '管理員發放'), ('LIVE_GIFT', '直播赠送'), ('EXCHANGE', '兌換'), ('WITHDRAW', '提現'), ('ACTIVITY_EXPENSE', '活動消費'), ('BOX', '开启元气宝盒')], max_length=20, verbose_name='流水类型'),
        ),
    ]
