# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-05 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20170904_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='date_update_vip',
            field=models.DateTimeField(blank=True, null=True, verbose_name='VIP等级更新时间'),
        ),
    ]
