# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 16:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20170710_1139'),
        ('core', '0017_remove_prizetransition_prize_count'),
        ('core', '0014_merge_20170710_1025'),
    ]

    operations = [
    ]
