# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-26 19:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0018_auto_20170726_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='badgerecords_owned', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'db_table': 'core_badge_record',
                'verbose_name_plural': '徽章記錄',
                'verbose_name': '徽章記錄',
            },
        ),
        migrations.RemoveField(
            model_name='badge',
            name='author',
        ),
        migrations.AddField(
            model_name='badgerecord',
            name='badge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='core.Badge', verbose_name='徽章'),
        ),
        migrations.AlterUniqueTogether(
            name='badgerecord',
            unique_together=set([('author', 'badge')]),
        ),
    ]
