# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-11 16:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_merge_20170710_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='starmissionachievement',
            name='live',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='star_mission_achievement', to='core.Live', verbose_name='直播'),
        ),
    ]
