# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-05 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_member_date_update_vip'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_demote',
            field=models.BooleanField(default=False, verbose_name='是否被降级'),
        ),
    ]
