# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-12 10:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_prizecategory_is_vip_only'),
        ('core', '0019_auto_20170711_2132'),
    ]

    operations = [
    ]
