# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-12 15:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_starmissionachievement_live'),
        ('core', '0019_auto_20170711_2132'),
    ]

    operations = [
    ]
