# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-26 20:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20170726_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgerecord',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='獲得時間'),
            preserve_default=False,
        ),
    ]
