# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-01 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_badgerecord_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymission',
            name='content',
            field=models.TextField(blank=True, default='', verbose_name='内容(規則)'),
        ),
    ]
