# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 15:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_merge_20170712_1505'),
        ('core', '0020_live_like_count'),
    ]

    operations = [
    ]
