# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-28 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_movie_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='type',
            field=models.CharField(blank=True, choices=[('MOVIE', '影片'), ('LIVE', '直播')], default='', help_text='當影片分類爲熱門視頻時需要選擇', max_length=20, verbose_name='類型'),
        ),
    ]
