# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-12 17:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_merge_20170712_1553'),
        ('core', '0020_merge_20170712_1052'),
    ]

    operations = [
    ]
