# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-04 15:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20170904_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityparticipation',
            name='diamond_transaction',
        ),
        migrations.AddField(
            model_name='activityparticipation',
            name='first_diamond_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_activity_participation', to='core.CreditDiamondTransaction', verbose_name='第一阶段钻石奖励记录'),
        ),
    ]
