# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-01 15:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_base', '0003_auto_20170726_1618'),
        ('core', '0021_familymission_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymission',
            name='logo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='family_mission', to='django_base.ImageModel', verbose_name='任务海报'),
        ),
    ]
