# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-13 11:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20170712_2000'),
        ('core', '0022_merge_20170712_1724'),
    ]

    operations = [
    ]
