# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-28 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20170728_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='hot_tag',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='熱門標籤'),
        ),
    ]
