# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 21:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20170713_1730'),
        ('core', '0022_merge_20170712_1724'),
    ]

    operations = [
    ]
