# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-02 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_familymember_is_ban'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='is_ban',
            field=models.BooleanField(default=True, verbose_name='是否需要验证'),
        ),
        migrations.AlterField(
            model_name='creditcointransaction',
            name='type',
            field=models.CharField(choices=[('ADMIN', '管理員發放'), ('LIVE_GIFT', '直播赠送'), ('RECHARGE', '充值'), ('EXCHANGE', '兌換'), ('BOX', '打開元氣寶盒'), ('BARRAGE', '發送彈幕消費'), ('FAMILY_MODIFY', '家族長修改頭銜')], max_length=20, verbose_name='流水类型'),
        ),
    ]
