# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-05 17:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20170904_1542'),
        ('core', '0019_member_is_demote'),
    ]

    operations = [
    ]
