# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-28 16:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_movie_hot_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='hot_tag',
        ),
    ]
