# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-06 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_merge_20170905_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='amount_extend',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='VIP续等余额'),
        ),
    ]
