# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-13 23:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_merge_20170713_1113'),
        ('core', '0024_merge_20170713_2127'),
    ]

    operations = [
    ]
