# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-29 14:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_movie_hot_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='celebritycategory',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='celebrity_categories', to='core.Activity', verbose_name='活動'),
        ),
        migrations.AddField(
            model_name='celebritycategory',
            name='live_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='celebrity_categories', to='core.LiveCategory', verbose_name='直播分類'),
        ),
        migrations.AddField(
            model_name='celebritycategory',
            name='type',
            field=models.CharField(blank=True, choices=[('LIVE', '直播'), ('ACTIVITY', '活動')], max_length=20, null=True, verbose_name='分類類別'),
        ),
    ]
