# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-02 09:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20170802_0939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='family',
            old_name='is_ban',
            new_name='is_verify',
        ),
    ]
