# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-14 10:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20170714_0912'),
        ('core', '0024_merge_20170713_2127'),
    ]

    operations = [
    ]
