# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-31 09:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20170729_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailycheckinlog',
            name='prize_coin_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.CreditCoinTransaction', verbose_name='奖励金币流水记录'),
        ),
    ]
