# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-07 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_member_amount_extend'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='名称')),
                ('is_del', models.BooleanField(default=False, verbose_name='已删除')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('is_sticky', models.BooleanField(default=False, verbose_name='是否置顶')),
                ('sorting', models.SmallIntegerField(default=0, help_text='数字越大越靠前', verbose_name='排序')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('amount', models.IntegerField(verbose_name='经验值')),
                ('type', models.CharField(choices=[('LOGIN', '登录'), ('SHARE', '分享'), ('RECEIVE', '收礼'), ('SEND', '送礼'), ('WATCH', '观看直播'), ('LIVE', '直播'), ('OTHER', '其他')], max_length=10, verbose_name='类型')),
            ],
            options={
                'verbose_name': '经验流水',
                'db_table': 'core_experience_transaction',
                'verbose_name_plural': '经验流水',
            },
        ),
        migrations.AlterModelOptions(
            name='loginrecord',
            options={'verbose_name': '登录记录', 'verbose_name_plural': '登录记录'},
        ),
        migrations.RemoveField(
            model_name='member',
            name='experience',
        ),
        migrations.AddField(
            model_name='member',
            name='current_level_experience',
            field=models.IntegerField(default=0, verbose_name='当前等级经验'),
        ),
        migrations.AddField(
            model_name='member',
            name='large_level',
            field=models.IntegerField(default=1, verbose_name='大等级'),
        ),
        migrations.AddField(
            model_name='member',
            name='small_level',
            field=models.IntegerField(default=0, verbose_name='小等级'),
        ),
        migrations.AddField(
            model_name='member',
            name='total_experience',
            field=models.IntegerField(default=0, verbose_name='总经验值'),
        ),
        migrations.AlterModelTable(
            name='loginrecord',
            table='core_login_record',
        ),
    ]
