# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-04 11:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20170802_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailycheckinlog',
            name='coin_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_check_in_log', to='core.CreditCoinTransaction', verbose_name='奖励金币记录'),
        ),
    ]
