# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-14 10:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_merge_20170713_2305'),
        ('core', '0025_merge_20170714_1056'),
    ]

    operations = [
    ]
