# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-14 11:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0025_merge_20170714_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditStarIndexReceiverTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='金额')),
                ('remark', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('user_credit', models.ForeignKey(blank=True, help_text='即余额减少的用户', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creditstarindexreceivertransactions_credit', to=settings.AUTH_USER_MODEL, verbose_name='贷方用户')),
                ('user_debit', models.ForeignKey(blank=True, help_text='即余额增加的用户', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creditstarindexreceivertransactions_debit', to=settings.AUTH_USER_MODEL, verbose_name='借方用户')),
            ],
            options={
                'verbose_name': '星光指数（元氣）流水（收礼）',
                'verbose_name_plural': '星光指数（元氣）流水（收礼）',
                'db_table': 'core_credit_star_index_receiver_transaction',
            },
        ),
        migrations.CreateModel(
            name='CreditStarIndexSenderTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='金额')),
                ('remark', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('user_credit', models.ForeignKey(blank=True, help_text='即余额减少的用户', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creditstarindexsendertransactions_credit', to=settings.AUTH_USER_MODEL, verbose_name='贷方用户')),
                ('user_debit', models.ForeignKey(blank=True, help_text='即余额增加的用户', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creditstarindexsendertransactions_debit', to=settings.AUTH_USER_MODEL, verbose_name='借方用户')),
            ],
            options={
                'verbose_name': '星光指数（元氣）流水（送礼）',
                'verbose_name_plural': '星光指数（元氣）流水（送礼）',
                'db_table': 'core_credit_star_index_sender_transaction',
            },
        ),
        migrations.RemoveField(
            model_name='creditstarindextransaction',
            name='user_credit',
        ),
        migrations.RemoveField(
            model_name='creditstarindextransaction',
            name='user_debit',
        ),
        migrations.AlterModelOptions(
            name='creditstartransaction',
            options={'verbose_name': '星星（元气）流水', 'verbose_name_plural': '星星（元气）流水'},
        ),
        migrations.RemoveField(
            model_name='prizeorder',
            name='prize_transaction',
        ),
        migrations.RemoveField(
            model_name='prizeorder',
            name='star_index_transaction',
        ),
        migrations.AddField(
            model_name='prize',
            name='price_type',
            field=models.CharField(choices=[('COIN', '金币'), ('STAR', '元气')], default='COIN', max_length=20, verbose_name='价格单位'),
        ),
        migrations.AddField(
            model_name='prizeorder',
            name='receiver_prize_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prize_orders_as_receiver', to='core.PrizeTransaction', verbose_name='礼物记录'),
        ),
        migrations.AddField(
            model_name='prizeorder',
            name='sender_prize_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prize_orders_as_sender', to='core.PrizeTransaction', verbose_name='礼物记录'),
        ),
        migrations.AlterField(
            model_name='prize',
            name='price',
            field=models.IntegerField(default=0, verbose_name='价格（金币/元气）'),
        ),
        migrations.AlterField(
            model_name='prizeorder',
            name='star_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prize_orders', to='core.CreditStarTransaction', verbose_name='观众消耗元氣记录'),
        ),
        migrations.DeleteModel(
            name='CreditStarIndexTransaction',
        ),
        migrations.AddField(
            model_name='prizeorder',
            name='receiver_star_index_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prize_orders', to='core.CreditStarIndexReceiverTransaction', verbose_name='主播元气指數记录'),
        ),
        migrations.AddField(
            model_name='prizeorder',
            name='sender_star_index_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prize_orders', to='core.CreditStarIndexSenderTransaction', verbose_name='觀衆元气指數记录'),
        ),
    ]
