# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-31 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_dailycheckinlog_prize_coin_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeevent',
            name='informs',
            field=models.ManyToManyField(blank=True, related_name='activeevents', to='core.Inform', verbose_name='举报信息'),
        ),
    ]
