# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-07 15:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20170907_1438'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experiencetransaction',
            old_name='amount',
            new_name='experience',
        ),
    ]
