# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-04 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_dailycheckinlog_coin_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailycheckinlog',
            name='is_continue',
            field=models.BooleanField(default=True, verbose_name='连签奖励'),
        ),
        migrations.AlterField(
            model_name='creditcointransaction',
            name='type',
            field=models.CharField(choices=[('ADMIN', '管理員發放'), ('LIVE_GIFT', '直播赠送'), ('RECHARGE', '充值'), ('EXCHANGE', '兌換'), ('BOX', '打開元氣寶盒'), ('BARRAGE', '發送彈幕消費'), ('FAMILY_MODIFY', '家族長修改頭銜'), ('DAILY', '每日签到获得')], max_length=20, verbose_name='流水类型'),
        ),
        migrations.AlterField(
            model_name='creditstartransaction',
            name='type',
            field=models.CharField(choices=[('LIVE_GIFT', '直播赠送'), ('EARNING', '任務獲得'), ('ADMIN', '後臺補償'), ('DAILY', '签到获得')], max_length=20, verbose_name='流水类型'),
        ),
    ]
