# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-03 16:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_activeevent_informs'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitypage',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activitypage',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.AddField(
            model_name='activitypage',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否有效'),
        ),
        migrations.AddField(
            model_name='activitypage',
            name='is_del',
            field=models.BooleanField(default=False, verbose_name='已删除'),
        ),
        migrations.AddField(
            model_name='activitypage',
            name='is_sticky',
            field=models.BooleanField(default=False, verbose_name='是否置顶'),
        ),
        migrations.AddField(
            model_name='activitypage',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='名称'),
        ),
        migrations.AddField(
            model_name='activitypage',
            name='sorting',
            field=models.SmallIntegerField(default=0, help_text='数字越大越靠前', verbose_name='排序'),
        ),
    ]
