# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-14 16:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20170714_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extraprize',
            name='prize',
        ),
        migrations.AddField(
            model_name='extraprize',
            name='prize_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extra_prizes', to='core.PrizeCategory', verbose_name='礼物分類'),
        ),
    ]
