# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-07 16:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20170907_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityparticipation',
            name='experience_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_participation', to='core.ExperienceTransaction', verbose_name='经验流水'),
        ),
        migrations.AddField(
            model_name='dailycheckinlog',
            name='sign_experience_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_check_in_log', to='core.ExperienceTransaction', verbose_name='签到经验流水'),
        ),
        migrations.AlterField(
            model_name='experiencetransaction',
            name='type',
            field=models.CharField(choices=[('SIGN', '登录'), ('SHARE', '分享'), ('RECEIVE', '收礼'), ('SEND', '送礼'), ('WATCH', '观看直播'), ('LIVE', '直播'), ('LIVE', '活动'), ('OTHER', '其他')], max_length=10, verbose_name='类型'),
        ),
    ]
