# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-14 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20170714_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='prize',
            name='type',
            field=models.CharField(choices=[('NORMAL', '普通款'), ('SPECIAL', '特殊款')], default='NORMAL', max_length=20, verbose_name='礼物类型'),
        ),
    ]
