# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 22:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20170803_1640'),
        ('core', '0023_familymember_is_ban'),
    ]

    operations = [
    ]
