# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-07 17:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0029_auto_20170907_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencetransaction',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiencetransactions_owned', to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
    ]
