# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-05 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20170805_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymissionachievement',
            name='status',
            field=models.CharField(blank=True, choices=[(('GET',), '领取任务'), (('ACHIEVE',), '完成任务未领取奖励'), (('FINISH',), '完成任务已领取奖励')], max_length=20, null=True, verbose_name='任务状态'),
        ),
    ]
