# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-07 14:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20170805_1759'),
        ('core', '0029_merge_20170806_2230'),
    ]

    operations = [
    ]
