# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-11 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_family_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='credit_diamond_extend',
            field=models.DecimalField(decimal_places=2, default=0, help_text='每贈送累計150鑽石獎勵經驗，用以保存多出的部分用作下次累加', max_digits=18, verbose_name='贈送鑽石餘額'),
        ),
        migrations.AddField(
            model_name='member',
            name='debit_diamond_extend',
            field=models.DecimalField(decimal_places=2, default=0, help_text='每獲贈累計150鑽石獎勵經驗，用以保存多出的部分用作下次累加', max_digits=18, verbose_name='收禮鑽石餘額'),
        ),
        migrations.AlterField(
            model_name='prizetransaction',
            name='type',
            field=models.CharField(choices=[('LIVE_RECEIVE', '直播獲得'), ('LIVE_SEND_BUY', '直播赠送-購買'), ('LIVE_SEND_BAG', '直播贈送-揹包'), ('ACTIVITY_GAIN', '活動獲得'), ('STAR_BOX_GAIN', '元氣寶盒獲得'), ('STAR_VIP_GAIN', 'VIP回馈獲得')], max_length=20, verbose_name='流水类型'),
        ),
    ]
