# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-15 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_merge_20170807_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='live',
            name='is_hot_recommended',
            field=models.BooleanField(default=False, verbose_name='是否为热门推荐'),
        ),
        migrations.AddField(
            model_name='live',
            name='is_index_recommended',
            field=models.BooleanField(default=False, verbose_name='是否为首次推荐'),
        ),
    ]
