# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_merge_20170807_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='experience',
            field=models.IntegerField(default=0, verbose_name='经验值'),
        ),
    ]
