# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-11 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20170911_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='live_extend',
            field=models.IntegerField(default=0, help_text='每直播累计30分钟奖励经验，用以保存多出的部分下次累加', verbose_name='直播擅长余额'),
        ),
        migrations.AddField(
            model_name='member',
            name='watch_live_extend',
            field=models.IntegerField(default=0, help_text='每观看直播累计30分钟奖励经验，用以保存多出的部分用作下次累加', verbose_name='观看直播时长余额'),
        ),
    ]
