# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-12 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_merge_20170807_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='informs',
            field=models.ManyToManyField(blank=True, related_name='members', to='core.Inform', verbose_name='举报信息'),
        ),
    ]
