# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_member_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='vip_level',
            field=models.IntegerField(default=0, verbose_name='VIP等级'),
        ),
    ]
