# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-11 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20170911_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='is_demote',
        ),
        migrations.AddField(
            model_name='member',
            name='is_first_prize',
            field=models.BooleanField(default=True, help_text='当送礼时为真，则为首次送礼，享受新人经验奖励', verbose_name='是否首次送礼'),
        ),
    ]
