# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-15 17:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20170815_0955'),
        ('core', '0034_member_informs'),
    ]

    operations = [
    ]
