# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-17 16:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_merge_20170815_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='live',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lives', to='core.LiveCategory', verbose_name='直播分类'),
        ),
    ]
