# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-13 09:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_livecategory_district'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livecategory',
            name='district',
        ),
    ]
