# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-13 10:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20170912_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailycheckinlog',
            name='coin_transaction',
        ),
        migrations.AddField(
            model_name='dailycheckinlog',
            name='prize_experience_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ExperienceTransaction', verbose_name='奖励经验记录'),
        ),
        migrations.AlterField(
            model_name='creditcointransaction',
            name='type',
            field=models.CharField(choices=[('ADMIN', '管理員發放'), ('LIVE_GIFT', '直播赠送'), ('RECHARGE', '充值'), ('EXCHANGE', '兌換'), ('BOX', '打開元氣寶盒'), ('BARRAGE', '發送彈幕消費'), ('FAMILY_MODIFY', '家族長修改頭銜'), ('DAILY', '每日签到获得'), ('ACTIVITY', '活动'), ('MISSION', '任務')], max_length=20, verbose_name='流水类型'),
        ),
    ]
