# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-14 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_remove_livecategory_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='live',
            name='date_replay',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最近一次重播开始时间'),
        ),
    ]
