# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-23 10:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_member_vip_level'),
        ('core', '0038_auto_20170821_1614'),
    ]

    operations = [
    ]
