# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-23 10:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_activeevent_like_count'),
        ('core', '0035_member_vip_level'),
    ]

    operations = [
    ]
