# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-15 12:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_live_date_replay'),
        ('core', '0038_auto_20170913_1007'),
    ]

    operations = [
    ]
