# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-21 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_merge_20170915_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='relative_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='相对id'),
        ),
    ]
