# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-24 16:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20170823_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='live',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='core.Live', verbose_name='直播'),
        ),
    ]
