# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-24 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_movie_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='播放次数'),
        ),
    ]
