# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-21 11:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_auto_20170919_1155'),
        ('core', '0041_member_relative_id'),
    ]

    operations = [
    ]
