# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-24 16:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_movie_live'),
        ('core', '0042_movie_view_count'),
    ]

    operations = [
    ]
