# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-23 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_merge_20170921_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='prize',
            name='vip_limit',
            field=models.IntegerField(default=0, verbose_name='VIP等级'),
        ),
        migrations.AlterField(
            model_name='creditcointransaction',
            name='type',
            field=models.CharField(choices=[('ADMIN', '管理員發放'), ('LIVE_GIFT', '直播赠送'), ('RECHARGE', '充值'), ('EXCHANGE', '兌換'), ('BOX', '打開元氣寶盒'), ('BARRAGE', '發送彈幕消費'), ('FAMILY_MODIFY', '家族長修改頭銜'), ('DAILY', '每日签到获得'), ('ACTIVITY', '活动'), ('MISSION', '任務'), ('ENTER_LIVE', '收费直播间'), ('VIP', 'vip赠送')], max_length=20, verbose_name='流水类型'),
        ),
        migrations.AlterField(
            model_name='creditdiamondtransaction',
            name='type',
            field=models.CharField(choices=[('ADMIN', '管理員發放'), ('LIVE_GIFT', '直播赠送'), ('EXCHANGE', '兌換'), ('WITHDRAW', '提現'), ('ACTIVITY_EXPENSE', '活動消費'), ('BOX', '开启元气宝盒'), ('VIP', 'VIP赠送')], max_length=20, verbose_name='流水类型'),
        ),
    ]
