# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-26 09:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_base', '0009_merge_20170815_1712'),
        ('core', '0044_auto_20170923_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='live',
            name='cover',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lives', to='django_base.ImageModel', verbose_name='封面图'),
        ),
    ]
