# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-26 18:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_member_is_vip_demand'),
        ('core', '0045_live_cover'),
    ]

    operations = [
    ]
