# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-27 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_live_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='live',
            name='date_response',
            field=models.DateTimeField(blank=True, help_text='前段每一分钟更新一次这个字段，如果5分钟检测没有更新自动关直播', null=True, verbose_name='响应时间'),
        ),
    ]
