# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-29 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_livewatchlog_date_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailycheckinlog',
            name='continue_check_in',
            field=models.IntegerField(default=1, verbose_name='连续签到天数'),
        ),
    ]
