# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-27 16:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_livewatchlog_date_response'),
        ('core', '0046_merge_20170926_1800'),
    ]

    operations = [
    ]
