# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-29 12:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_merge_20170927_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveRecordLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appid', models.IntegerField(default=0, verbose_name='推流应用id')),
                ('t', models.IntegerField(default=0, verbose_name='有效时间')),
                ('channel_id', models.CharField(help_text='同stream_id', max_length=25, verbose_name='直播码')),
                ('video_id', models.CharField(max_length=100, verbose_name='vid')),
                ('video_url', models.CharField(max_length=255, verbose_name='下载地址')),
                ('file_size', models.IntegerField(default=0, verbose_name='文件大小')),
                ('start_time', models.IntegerField(default=0, verbose_name='分片开始时间戳')),
                ('end_time', models.IntegerField(default=0, verbose_name='分片结束时间戳')),
                ('file_id', models.CharField(max_length=100, verbose_name='file_id')),
                ('file_format', models.CharField(max_length=20, verbose_name='文件格式')),
                ('record_file_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='录制文件id')),
                ('duration', models.IntegerField(default=0, verbose_name='推流时长')),
                ('stream_id', models.CharField(help_text='标志事件源于哪一条直播流', max_length=25, verbose_name='直播码')),
                ('stream_param', models.TextField(blank=True, null=True, verbose_name='推流url参数')),
                ('event_type', models.IntegerField(choices=[(0, 0), (1, 1), (100, 100), (200, 200)], default=100, verbose_name='事件类型')),
                ('sign', models.CharField(max_length=100, verbose_name='安全签名')),
                ('live', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_logs', to='core.Live', verbose_name='直播')),
            ],
            options={
                'db_table': 'core_live_record_log',
                'verbose_name': '直播录播记录',
                'verbose_name_plural': '直播录播记录',
            },
        ),
    ]
