# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-29 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_merge_20170927_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='live',
            name='is_record',
            field=models.BooleanField(default=False, help_text='如果设置錄制，推流同時增加錄制功能', verbose_name='是否錄制'),
        ),
    ]
