# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-29 15:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_auto_20170929_1512'),
        ('core', '0049_live_is_record'),
    ]

    operations = [
    ]
