# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-29 15:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_dailycheckinlog_continue_check_in'),
        ('core', '0051_merge_20170929_1526'),
    ]

    operations = [
    ]
