# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-30 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_merge_20170929_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='stream_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='直播码'),
        ),
    ]
