# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-30 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_member_stream_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liverecordlog',
            name='channel_id',
            field=models.CharField(help_text='(channel_id)同stream_id', max_length=50, verbose_name='直播码'),
        ),
        migrations.AlterField(
            model_name='liverecordlog',
            name='stream_id',
            field=models.CharField(help_text='(stream_id)标志事件源于哪一条直播流', max_length=50, verbose_name='直播码'),
        ),
    ]
