# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-30 17:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_auto_20170930_1630'),
        ('core', '0054_auto_20170930_1432'),
    ]

    operations = [
    ]
