# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-11 18:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_merge_20171009_1009'),
        ('core', '0055_merge_20170930_1728'),
    ]

    operations = [
    ]
