# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-16 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='project',
            field=models.CharField(blank=True, default='', help_text='如果有多个后台模块，通过这个字段区分', max_length=50, verbose_name='项目名称'),
        ),
    ]
