# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 11:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('django_base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('level', models.IntegerField(choices=[(0, '调试'), (1, '信息'), (2, '警告'), (3, '错误'), (4, '致命')], verbose_name='日志级别')),
                ('target_id', models.PositiveIntegerField()),
                ('content', models.TextField(help_text='JSON格式的日志数据内容，具体使用可以根据应用实际情况而定', verbose_name='日志内容')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adminlogs_owned', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('target_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': '管理日志',
                'verbose_name_plural': '管理日志',
                'db_table': 'base_admin_log',
            },
        ),
    ]
