# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-03 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_base', '0003_auto_20170726_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='value',
            field=models.CharField(blank=True, default='', max_length=2250, verbose_name='选项值'),
        ),
    ]
