# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 11:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('django_base', '0003_auto_20170628_1553'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='usermark',
        #     name='date_created',
        #     field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
        #     preserve_default=False,
        # ),
        # migrations.AddField(
        #     model_name='usermark',
        #     name='date_updated',
        #     field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        # ),
        # migrations.AddField(
        #     model_name='usermark',
        #     name='is_active',
        #     field=models.BooleanField(default=True, verbose_name='是否有效'),
        # ),
        # migrations.AddField(
        #     model_name='usermark',
        #     name='is_del',
        #     field=models.BooleanField(default=False, verbose_name='已删除'),
        # ),
        # migrations.AddField(
        #     model_name='usermark',
        #     name='is_sticky',
        #     field=models.BooleanField(default=False, verbose_name='是否置顶'),
        # ),
        # migrations.AddField(
        #     model_name='usermark',
        #     name='name',
        #     field=models.CharField(blank=True, default='', max_length=255, verbose_name='名称'),
        # ),
        # migrations.AddField(
        #     model_name='usermark',
        #     name='sorting',
        #     field=models.SmallIntegerField(default=0, help_text='数字越大越靠前', verbose_name='排序'),
        # ),
    ]
