# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-10 10:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_base', '0003_auto_20170628_1553'),
        ('django_base', '0003_auto_20170705_1128'),
    ]

    operations = [
    ]
