# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 14:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_base', '0003_auto_20170705_1128'),
        ('django_base', '0003_auto_20170704_0001'),
    ]

    operations = [
    ]
