# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 16:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_base', '0004_auto_20170710_1139'),
        ('django_base', '0004_merge_20170710_1025'),
    ]

    operations = [
    ]
