# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-15 09:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('django_base', '0005_broadcast_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermark',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='记录时间'),
            preserve_default=False,
        ),
    ]
