# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 20:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_base', '0006_auto_20170711_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermark',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='usermark',
            name='date_updated',
        ),
        migrations.RemoveField(
            model_name='usermark',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='usermark',
            name='is_del',
        ),
        migrations.RemoveField(
            model_name='usermark',
            name='is_sticky',
        ),
        migrations.RemoveField(
            model_name='usermark',
            name='name',
        ),
        migrations.RemoveField(
            model_name='usermark',
            name='sorting',
        ),
    ]
