# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-15 17:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_base', '0006_usermark_date_created'),
        ('django_base', '0007_auto_20170815_1627'),
    ]

    operations = [
    ]
