# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-15 17:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_base', '0008_merge_20170815_1710'),
        ('django_base', '0008_auto_20170815_1643'),
    ]

    operations = [
    ]
