# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-26 15:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_base', '0009_merge_20170815_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='users_read',
            field=models.ManyToManyField(blank=True, related_name='user_read', to=settings.AUTH_USER_MODEL, verbose_name='已阅读用户'),
        ),
    ]
