# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-28 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_base', '0010_message_users_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermark',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='是否已读'),
        ),
    ]
