# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-11 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrecord',
            name='platform',
            field=models.CharField(blank=True, choices=[('BALANCE', '余额支付'), ('ALIPAY', '支付宝'), ('WXPAY', '微信支付'), ('APP', 'Buy in app'), ('PAYPAL', 'Paypal')], default='', max_length=20, verbose_name='支付平台'),
        ),
    ]
